# Generated by Django 5.2.3 on 2025-07-02 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
