# Generated by Django 5.0.3 on 2025-08-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('THOUGHT', 'Ma pensée'), ('ADHERE', "J'adhère"), ('SUPPORT', 'Je soutiens'), ('ALTERNATIVE', 'Je propose une alternative'), ('CLARIFY', 'Je demande des précisions')], default='THOUGHT', max_length=20),
        ),
    ]
