# Generated by Django 5.0.3 on 2025-08-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmessage',
            name='is_read',
            field=models.ManyToManyField(blank=True, related_name='read_club_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.clubmessage'),
        ),
    ]
