# Generated by Django 5.2.3 on 2025-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publication_disliked_by_publication_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
