# Generated by Django 5.2.3 on 2025-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/%d/'),
        ),
    ]
