# Generated by Django 5.0.3 on 2025-08-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clubmessage_is_read_clubmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('RELATIONSHIP', 'En couple'), ('MARRIED', 'Marié(e)'), ('COMPLICATED', "C'est compliqué")], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
