# Generated by Django 5.0.3 on 2025-08-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_hobbies_user_partner_user_relationship_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='media',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='medias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.publication')),
            ],
        ),
    ]
