# Generated by Django 5.2.3 on 2025-07-03 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
