# Generated by Django 5.2.3 on 2025-07-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_subscribers_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.reaction'),
        ),
    ]
